#!/usr/bin/env node
// =============================================================================
// build-exe.js — builds WTS-Modbus-Bridge-Setup.exe (Node.js single executable application).
//
//   node tools/modbus-bridge/exe/build-exe.js [--out dist] [--node-exe path\to\node.exe] [--download]
//                                             [--bundle-only] [--postject "npx --yes postject@1.0.0-alpha.6"]
//
//   1. bundle   modbus-bridge.js + bridge-app.js → <out>/sea-main.js (one CommonJS file: a SEA main
//               script can require() built-in modules only)
//   2. blob     node --experimental-sea-config sea-config.json → <out>/sea-prep.blob
//               (useCodeCache false, disableExperimentalSEAWarning true)
//   3. node.exe Windows: this node.exe (process.execPath); elsewhere --node-exe, or --download fetches
//               node.exe of THIS Node version from nodejs.org (SHA-256 checked against SHASUMS256.txt).
//               The blob only runs in the same Node version that wrote it.
//   4. copy     → <out>/WTS-Modbus-Bridge-Setup.exe, Authenticode signature stripped (it would be invalid
//               after the injection)
//   5. inject   postject … NODE_SEA_BLOB sea-prep.blob --sentinel-fuse NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2
//   6. patch    PE subsystem WINDOWS_CUI (3) → WINDOWS_GUI (2): no console window, ever (Node reopens the
//               missing stdio handles on "nul", so console output is simply discarded)
//
// require()-able: { bundle, bundleText, build, OUT_NAME, FUSE }.
// =============================================================================
'use strict';

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const https = require('https');
const vm = require('vm');
const { spawnSync } = require('child_process');
const pe = require('./pe.js');

const HERE = __dirname;
const TOOLS = path.resolve(HERE, '..');
const OUT_NAME = 'WTS-Modbus-Bridge-Setup.exe';
const FUSE = 'NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2';
const POSTJECT = 'postject@1.0.0-alpha.6';

function stripShebang(s) { return String(s).replace(/^﻿/, '').replace(/^#![^\n]*\n/, ''); }
// One script: the bridge module evaluated into __WTS_BRIDGE__, then the launcher.
function bundleText() {
  const bridge = stripShebang(fs.readFileSync(path.join(TOOLS, 'modbus-bridge.js'), 'utf8'));
  const app = stripShebang(fs.readFileSync(path.join(HERE, 'bridge-app.js'), 'utf8'));
  const version = /const BRIDGE_VERSION = '([0-9.]+)'/.exec(bridge)[1];
  return [
    '// WTS Modbus Bridge v' + version + ' — single executable application bundle, GENERATED by tools/modbus-bridge/exe/build-exe.js',
    '// from tools/modbus-bridge/modbus-bridge.js and tools/modbus-bridge/exe/bridge-app.js. Do not edit.',
    "'use strict';",
    'const __WTS_BRIDGE__ = (function () {',
    '  const module = { exports: {} }, exports = module.exports;',
    '  (function (module, exports, require, __filename, __dirname) {',
    bridge,
    '  })(module, exports, require, __filename, __dirname);',
    '  return module.exports;',
    '})();',
    app,
    '',
  ].join('\n');
}
function bundle(outDir) {
  fs.mkdirSync(outDir, { recursive: true });
  const text = bundleText();
  new vm.Script(text, { filename: 'sea-main.js' });          // syntax check
  const file = path.join(outDir, 'sea-main.js');
  fs.writeFileSync(file, text);
  fs.writeFileSync(path.join(outDir, 'sea-config.json'), JSON.stringify({ main: 'sea-main.js', output: 'sea-prep.blob', disableExperimentalSEAWarning: true, useCodeCache: false }, null, 2) + '\n');
  return file;
}

function sha256(buf) { return crypto.createHash('sha256').update(buf).digest('hex'); }
function get(url, redirects) {
  return new Promise((resolve, reject) => {
    https.get(url, { headers: { 'User-Agent': 'wts-build-exe' } }, (res) => {
      if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location && (redirects || 0) < 5) { res.resume(); resolve(get(new URL(res.headers.location, url).href, (redirects || 0) + 1)); return; }
      if (res.statusCode !== 200) { res.resume(); reject(new Error(url + ': HTTP ' + res.statusCode)); return; }
      const parts = []; res.on('data', (d) => parts.push(d)); res.on('end', () => resolve(Buffer.concat(parts))); res.on('error', reject);
    }).on('error', reject);
  });
}
async function downloadNodeExe(cacheDir) {
  const v = process.version, base = 'https://nodejs.org/dist/' + v + '/';
  const file = path.join(cacheDir, 'node-' + v + '-win-x64.exe');
  const sums = (await get(base + 'SHASUMS256.txt')).toString('utf8');
  const m = /^([0-9a-f]{64})\s+win-x64\/node\.exe$/m.exec(sums);
  if (!m) throw new Error('SHASUMS256.txt of ' + v + ' has no win-x64/node.exe');
  if (fs.existsSync(file) && sha256(fs.readFileSync(file)) === m[1]) return file;
  console.log('[build-exe] downloading ' + base + 'win-x64/node.exe');
  const exe = await get(base + 'win-x64/node.exe');
  if (sha256(exe) !== m[1]) throw new Error('node.exe SHA-256 mismatch');
  fs.mkdirSync(cacheDir, { recursive: true });
  fs.writeFileSync(file, exe);
  return file;
}
function run(cmd, args, opts) {
  console.log('[build-exe] ' + cmd + ' ' + args.join(' '));
  const shell = process.platform === 'win32' && /^npx$/.test(cmd);          // npx is npx.cmd on Windows
  if (shell) args = args.map((x) => (/[\s&()^|<>]/.test(x) ? '"' + x + '"' : x));   // a shell command line is not quoted by Node
  const r = spawnSync(cmd, args, Object.assign({ stdio: 'inherit', shell }, opts || {}));
  if (r.status !== 0) throw new Error(cmd + ' failed (' + (r.error ? r.error.message : 'exit ' + r.status) + ')');
}

async function build(o) {
  o = o || {};
  const out = path.resolve(o.out || path.join(HERE, 'dist'));
  bundle(out);
  console.log('[build-exe] bundled ' + path.join(out, 'sea-main.js'));
  if (o.bundleOnly) return { out };
  run(process.execPath, ['--experimental-sea-config', 'sea-config.json'], { cwd: out });
  let nodeExe = o.nodeExe;
  if (!nodeExe && process.platform === 'win32') nodeExe = process.execPath;
  if (!nodeExe && o.download) nodeExe = await downloadNodeExe(path.join(out, 'cache'));
  if (!nodeExe) throw new Error('no node.exe: run on Windows, or pass --node-exe <node.exe of ' + process.version + '> or --download');
  const exe = path.join(out, OUT_NAME);
  const src = fs.readFileSync(nodeExe);
  const info = pe.readPe(src);
  if (info.machine !== 0x8664) console.warn('[build-exe] WARNING: ' + nodeExe + ' is not x64 (machine 0x' + info.machine.toString(16) + ')');
  fs.writeFileSync(exe, pe.stripSignature(src));
  const pj = (o.postject || 'npx --yes ' + POSTJECT).split(' ');
  run(pj[0], pj.slice(1).concat([exe, 'NODE_SEA_BLOB', path.join(out, 'sea-prep.blob'), '--sentinel-fuse', FUSE]));
  const buf = fs.readFileSync(exe);
  pe.setSubsystem(buf, pe.SUBSYSTEM.WINDOWS_GUI);
  fs.writeFileSync(exe, buf);
  const chk = pe.readPe(fs.readFileSync(exe));
  if (chk.subsystem !== pe.SUBSYSTEM.WINDOWS_GUI) throw new Error('subsystem patch failed');
  if (buf.indexOf(FUSE + ':1') < 0) throw new Error('the SEA fuse was not flipped — postject did not inject the blob');
  const hash = sha256(buf);
  console.log('[build-exe] ' + exe + '  ' + (buf.length / 1048576).toFixed(1) + ' MB  sha256 ' + hash + '  (' + chk.magic + ', subsystem ' + chk.subsystem + ' = WINDOWS_GUI, node ' + process.version + ')');
  return { out, exe, sha256: hash, size: buf.length };
}

function parseArgv(argv) {
  const o = {};
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === '--out') o.out = argv[++i];
    else if (a === '--node-exe') o.nodeExe = argv[++i];
    else if (a === '--download') o.download = true;
    else if (a === '--bundle-only') o.bundleOnly = true;
    else if (a === '--postject') o.postject = argv[++i];
    else throw new Error('unknown option ' + a);
  }
  return o;
}

module.exports = { bundle, bundleText, build, OUT_NAME, FUSE, POSTJECT };
if (require.main === module) {
  build(parseArgv(process.argv.slice(2))).catch((e) => { console.error('[build-exe] ERROR: ' + e.message); process.exit(1); });
}
